
development:
  adapter: postgresql
  encoding: unicode
  database: x_weibo_dev
  pool: 5
  username: Mac
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: x_weibo_test
  pool: 5
  username: Mac
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: x_weibo
  pool: 5
  username: Mac
  password:
